# Generated by Django 2.2.27 on 2022-03-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_recipeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='recipes', to='recipes.Tag'),
        ),
    ]
