# Generated by Django 2.2.27 on 2022-03-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220303_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='inredient',
            new_name='ingredient',
        ),
    ]
